Remove optimization to make jQuery compatible with Google's Polymer project
When Polymer platform is used together with jQuery, removed lines cause error:
> TypeError: Argument 1 of Window.getDefaultComputedStyle does not implement interface Element.

Since removal of this method doesn't break anything, and method was removed from specification, I think it is possible to merge this pull request without problems.